// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';


function set_title(str) {
  document.title = str;
  return /* () */0;
}

exports.set_title = set_title;
/* No side effect */
