// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';


function set_title(str) {
  document.title = str;
  return /* () */0;
}

var isEnabled = (
  (window.Notification) ? true : false
);

exports.set_title = set_title;
exports.isEnabled = isEnabled;
/* isEnabled Not a pure module */
