// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';


var minute = 60.0 * 1000.0;

var unixTimeShift = 17.0 * 60.0 * 60.0 * 1000.0;

function padWithZeros(str) {
  var match = str.length === 1;
  if (match) {
    return "0" + str;
  } else {
    return str;
  }
}

function toReadableString(value) {
  return padWithZeros(String(value | 0));
}

function formatTime(time) {
  var value = time.getSeconds();
  var seconds = padWithZeros(String(value | 0));
  var value$1 = time.getMinutes();
  var minutes = padWithZeros(String(value$1 | 0));
  var value$2 = time.getHours();
  var hours = padWithZeros(String(value$2 | 0));
  return hours + (":" + (minutes + (":" + seconds)));
}

function getTimerData(timeStart, timeEnd) {
  return formatTime(new Date(timeEnd - timeStart + unixTimeShift));
}

function getCountdownTimerData(timeStart, timeEnd, timeLimit) {
  var timeDiff = timeEnd - timeStart;
  return formatTime(new Date(timeLimit - timeDiff + unixTimeShift));
}

exports.minute = minute;
exports.unixTimeShift = unixTimeShift;
exports.padWithZeros = padWithZeros;
exports.toReadableString = toReadableString;
exports.formatTime = formatTime;
exports.getTimerData = getTimerData;
exports.getCountdownTimerData = getCountdownTimerData;
/* No side effect */
