// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';


function padWithZeros(str) {
  var match = str.length === 1;
  if (match) {
    return "0" + str;
  } else {
    return str;
  }
}

function toReadableString(value) {
  return padWithZeros(String(value | 0));
}

function getTimerData(timeStart, timeEnd) {
  var unixTimeShift = 17.0 * 60.0 * 60.0 * 1000.0;
  var timeDiff = new Date(timeEnd - timeStart + unixTimeShift);
  var value = timeDiff.getSeconds();
  var seconds = padWithZeros(String(value | 0));
  var value$1 = timeDiff.getMinutes();
  var minutes = padWithZeros(String(value$1 | 0));
  var value$2 = timeDiff.getHours();
  var hours = padWithZeros(String(value$2 | 0));
  return hours + (":" + (minutes + (":" + seconds)));
}

exports.padWithZeros = padWithZeros;
exports.toReadableString = toReadableString;
exports.getTimerData = getTimerData;
/* No side effect */
